spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_db
    username: postgres
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern=/static/**:
